modLoader="javafml"
loaderVersion="${mod_forge_version}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/storage-overhaul/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/storage-overhaul"
# logoFile="storage_overhaul.png"
# credits=""
authors="${mod_vendor}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://maxhenkel.de/update/storage_overhaul.json"
description='''A complete overhaul of storage containers'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${mod_forge_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mod_minecraft_version}]"
    ordering="NONE"
    side="BOTH"